### ISSUE TITLE
Negation Problem

### ISSUE THREAD

**Issue by emcardoso** [lives-group/TheoremProver#1]
As it is, some rules involving negation are not possible.
Investigate the use of the implication model (a -> F), where F is type no terms, as means to represent negation

**Comment by rodrigogribeiro** [comment]
Well, I think that this is just a desugaring problem since, after parsing, you can represent negation (like `~ A`, using Coq like syntax) as `A -> False`, and reuse all the machinery for implications.

**Comment by emcardoso** [comment]
What abou the Rule (Flase -> a) for any type a ? This rule allow us to conclude anything from a False type correct ? An so we have to make the lambca calculus type system's accept a term with such a type. I'm not so sure how do do it.

**Comment by rodrigogribeiro** [comment]
Just create a term of to represent `False` and type it using any type, since it should denote proofs of rule ex-falsum-quod-libet: from false, follows anything.

**Comment by emcardoso** [comment]
Solved !
