### ISSUE TITLE
Problem with NaughtElim

### ISSUE THREAD

**Issue by rodrigogribeiro** [lives-group/TheoremProver#5]
Hi guys!

I believe that the type of `NaughtElim` constructor is wrong. In my humble opinion, its type should be
`NaughtElim Term Type`, since it should denote the following rule

    Gamma |- e : False
    -------------------------
    Gamma |- NaughtElim e t : t

where t is a proposition. Note that this term should store what proposition it is proving, since it denote
the idea of from False it follows anything.

**Comment by emcardoso** [comment]
You are correct.
But we have already fixed that a while ago !
However we still fixing the shell rules for negation.
I have Mr. Baumgratz  on it rigth now ! I hope tomorrow it will be correct and operational again.
Thanks for the warning anyway.

**Comment by emcardoso** [comment]
Solved !
